.....E.....
======================================================================
ERROR: test_netflix_solve (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 97, in test_netflix_solve
    self.assertTrue(result < 1.0)
TypeError: unorderable types: function() < float()

----------------------------------------------------------------------
Ran 11 tests in 12.328s

FAILED (errors=1)
--- 10.268894910812378 seconds ---
